title: Susmita Mandal's Blog
description: > # this means to ignore newlines until "baseurl:"
  I'm a bioinformatician prepping for my PhD
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Susmita Mandal # add your name
author-img: susmita-mandal.jpg # add your photo
about-author: Future Scientist. Bioinformatician @ IISC Bangalore.
social-twitter: sushimndl
#social-facebook: # add your Facebook handle
social-github: sushimndl # add your Github handle
social-linkedin: sushimndl
#social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
